#### Importing the libraries.

In [4]:
import pandas as pd
import numpy as np

#### Loading the dataset

In [6]:
df = pd.read_csv('../data/raw/sales_data.csv')

In [7]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

#### Creating a Copy of the Dataset

In [8]:
# Creating a copy of the original dataset for data preparation.

df_prepared = df.copy()

#### Converting the Date Column

In [9]:
# Converting the Date column from object to datetime format.

df_prepared['Date'] = pd.to_datetime(
    df_prepared['Date']
)

In [10]:
# Checking the updated data types.

df_prepared.dtypes

Date                  datetime64[ns]
Store ID                      object
Product ID                    object
Category                      object
Region                        object
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Price                        float64
Discount                       int64
Weather Condition             object
Promotion                      int64
Competitor Pricing           float64
Seasonality                   object
Epidemic                       int64
Demand                         int64
dtype: object

#### Checking for Duplicate Records

In [11]:
# Even though the dataset may not contain duplicates, doule checking to validate this before modeling.

# Checking the number of duplicate rows in the dataset.

duplicate_count = df_prepared.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

#### Validating Missing Values

In [12]:
# Checking for missing values before preparing the dataset.

missing_values = df_prepared.isnull().sum()

print(missing_values)

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

#### Checking for Invalid Negative Values

In [14]:
# Defining the numerical columns for validation.

numerical_columns = [
    'Inventory Level',
    'Units Sold',
    'Units Ordered',
    'Price',
    'Discount',
    'Competitor Pricing',
    'Demand'
]


# Checking for negative values in the numerical columns.

for column in numerical_columns:
    
    negative_values = (
        df_prepared[column] < 0
    ).sum()
    
    print(
        f"{column}: {negative_values} negative values"
    )

Inventory Level: 0 negative values
Units Sold: 0 negative values
Units Ordered: 0 negative values
Price: 0 negative values
Discount: 0 negative values
Competitor Pricing: 0 negative values
Demand: 0 negative values

#### Validating Binary Columns

In [15]:
# Defining the binary columns for validation.

binary_columns = [
    'Promotion',
    'Epidemic'
]

# Checking the unique values in the binary columns.

for column in binary_columns:
    
    print(f"\n{column}:")
    print(df_prepared[column].unique())

Promotion:
[0 1]

Epidemic:
[0 1]

#### Converting Categorical Columns

In [17]:
# Defining the categorical columns.

categorical_columns = [
    'Store ID',
    'Product ID',
    'Category',
    'Region',
    'Weather Condition',
    'Seasonality'
]

# Converting the categorical columns to category data type.

for column in categorical_columns:
    
    df_prepared[column] = (
        df_prepared[column].astype('category')
    )

In [18]:
# Checking the updated data types after conversion.

df_prepared.dtypes

Date                  datetime64[ns]
Store ID                    category
Product ID                  category
Category                    category
Region                      category
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Price                        float64
Discount                       int64
Weather Condition           category
Promotion                      int64
Competitor Pricing           float64
Seasonality                 category
Epidemic                       int64
Demand                         int64
dtype: object

#### Sorting the Dataset by Date

In [19]:
# Sorting the dataset chronologically by date.

df_prepared = df_prepared.sort_values(
    by='Date'
).reset_index(
    drop=True
)

In [20]:
# Displaying the first few records after sorting by date.

df_prepared.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S004,P0013,Groceries,West,136,104,385,20.24,10,Snowy,0,18.90,Winter,0,110
2,2022-01-01,S004,P0012,Electronics,West,111,111,113,118.15,0,Snowy,0,133.46,Winter,0,103
3,2022-01-01,S004,P0011,Clothing,West,195,60,293,52.89,0,Snowy,0,62.29,Winter,0,61
4,2022-01-01,S004,P0010,Groceries,West,223,120,597,30.02,0,Snowy,0,29.15,Winter,0,128

#### Final Data Validation

In [21]:
# Checking the final dataset information.

df_prepared.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  datetime64[ns]
 1   Store ID            76000 non-null  category
 2   Product ID          76000 non-null  category
 3   Category            76000 non-null  category
 4   Region              76000 non-null  category
 5   Inventory Level     76000 non-null  int64
 6   Units Sold          76000 non-null  int64
 7   Units Ordered       76000 non-null  int64
 8   Price               76000 non-null  float64
 9   Discount            76000 non-null  int64
 10  Weather Condition   76000 non-null  category
 11  Promotion           76000 non-null  int64
 12  Competitor Pricing  76000 non-null  float64
 13  Seasonality         76000 non-null  category
 14  Epidemic            76000 non-null  int64
 15  Demand              76000 non-null  int64
dtypes: category(6), datetime64[ns](1), float64(2), int64(7)
memory usage: 6.2 MB

In [22]:
# Checking for missing values in the prepared dataset.

df_prepared.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [23]:
# Checking the final dataset shape.

print(
    "Final Dataset Shape:",
    df_prepared.shape
)

Final Dataset Shape: (76000, 16)

#### Saving the Prepared Dataset

In [24]:
# Saving the prepared dataset for the next stage of the project.

df_prepared.to_csv(
    '../data/processed/prepared_data.csv',
    index=False
)